"""
Django settings for conf project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from django.contrib.messages import constants as messages
from pathlib import Path
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv
import os
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#if DEBUG = FALSE 
ALLOWED_HOSTS = ["127.0.0.1","localhost"]


# Application definition
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
]

#Let Django app page do registry resources of the url link
APPLICATION_APPS= [
    'pages.apps.PagesConfig',   
    'accounts.apps.AccountsConfig',       
    'cart.apps.CartConfig',    
    'orders.apps.OrdersConfig',
    "blogs.apps.BlogsConfig",
    'reviews.apps.ReviewsConfig',
    'payment.apps.PaymentConfig',
    'coupons.apps.CouponsConfig',
]

THIRD_PARTY_APPS = ["debug_toolbar","widget_tweaks",'taggit','import_export']

INSTALLED_APPS = DJANGO_APPS + APPLICATION_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',    
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "erb8shop",
        "USER": "postgres",
        "PASSWORD": "1234",
        "HOST": "localhost",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LOCALE_PATHS = [os.path.join(BASE_DIR,'locale')] 

#TIME_ZONE = 'Asia/Hong_Kong'
TIME_ZONE = 'Asia/Shanghai'

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', _('English')),
    #('zh-Hant', _('Chinese')),
    ('zh-hant', _('Chinese')),
]

USE_I18N = True

USE_TZ = True #use time zone #some student need to set the line

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
#Generate a new static folder under the project root and define the erb8 project static path
STATIC_ROOT=os.path.join(BASE_DIR,'static') 
#set the newly created static folder path
STATIC_URL = 'static/' 
#this statement is used to scan all the static file in the project folder and copy thoses files to the newly created
#static folder
STATICFILES_DIRS =[os.path.join(BASE_DIR,'config/static')] 

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' #database default using big integer

#Config setting to store dynamic media file 
#and do config at urls.py
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'


#https://django-debug-toolbar.readthedocs.io/en/latest/installation.html
INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]
MESSAGE_TAGS = {
    messages.ERROR:'danger',
    messages.SUCCESS:'success',
    messages.INFO: "",
    50: "critical",
    messages.WARNING: 'warning',
    messages.INFO: 'info',
}

CART_SESSION_ID = 'cart'

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASS')


# Stripe settings
STRIPE_PUBLISHABLE_KEY = 'pk_test_51SrvamFjeVhyYFoh3twWqOKI3V358bkvVo2eCsWq8kjFtzso6RHP5q2iQXl57sX31GgbFpFvyVGWjrqmnMjAvTbZ000Hi65wnX' # Publishable key
STRIPE_SECRET_KEY = 'sk_test_51SrvamFjeVhyYFohyI4BhGYeuP0lXO5AtJDshndhURXOJ3WjLAjnKQ5XiqrnLD8O5IMj1NhxDtDvhvsG7Y9L6kLA00eC2a8jCi'      # Secret key
STRIPE_API_VERSION = '2022-08-01'
#STRIPE_WEBHOOK_SECRET = ''
